# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GphWTyRtvA2PYX2-XJEHMeuz16KMPfb
"""

print("Hello, Python")

oshi = "上田綺世"
stars = 5
print(oshi, stars)

items = ["上田綺世", "鈴木彩艶", "三笘薫"]

for item in items:
    print(item)

items = ["上田綺世", "鈴木彩艶", "三笘薫"]

for item in items:
    if len(item) == 4:
        print(item, "は4文字")

!pip install supabase

from supabase import create_client

url = "ここにProject URLを貼る"
key = "ここにanon keyを貼る"

supabase = create_client(url, key)
print("接続しました")

res = supabase.table("items").select("*").execute()
print(res.data)

for row in res.data:
    print(row["title"], "/", row["category"])

items = supabase.table("items").select("id").execute().data
first_id = items[0]["id"]
print(first_id)

rows = []
for i in range(1, 101):
    rows.append({
        "item_id": first_id,
        "body": f"テストコメント{i}",
        "stars": (i % 5) + 1
    })

print(len(rows))

supabase.table("comments").insert(rows).execute()
print("投入しました")

res = supabase.table("comments").select("*").execute()
print(len(res.data))

supabase.table("comments").delete().like("body", "テストコメント%").execute()

res = supabase.table("comments").select("*").execute()
print(len(res.data))